[package]
name = "rust_blockchain"
version = "0.1.0"
edition = "2018"

[dependencies]
chrono = "0.4"
rust-crypto = "0.2.36"
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"