[package]
name = "miner"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
spec = { path = "../spec" }

clap = { version = "3.2.8", features = ["derive"] }
isahc = "1.7.2"
serde_json = "1.0.81"